HTML/learning_logs/urls.py
""" 定义 learning_logs 的 URL 模式"""
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # 显示所有的主题
    path('topics/', views.topics, name='topics'),
    # 特定主题的详细页面
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # 用于添加新主题的网页
    path('new_topic/', views.new_topic, name='new_topic'),
    # # 用于添加新条目的页面
    # path()
]

HTML/ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

# urlpatterns 是一个包含路由规则的列表
urlpatterns = [
    # 第一个路由将以 “admin/” 开头的 URL 路由到 Django 的管理后台的 URL 配置。(http://example.com/admin/)
    path('admin/', admin.site.urls),
    # 第二个路由将根路径（空字符串）路由到名为 “learning_logs.urls” 模块中的 URL 配置。
    # include函数允许将 URL 路由规则分散到不同的模块中，这样每个应用可以有自己独立的urls.py文件来定义和管理它自己的路由规则。
    path('', include('learning_logs.urls')),
]

HTML/learning_logs/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        """返回一个表示条目的简单字符串"""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

HTML/learning_logs/forms.py
from django import forms
from .models import Topic, Entry
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


HTML/learning_logs/views.py
from django.shortcuts import render,redirect
from .models import Topic
from .forms import TopicForm
# Create your views here.


def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """显示所有主题"""
    # 从数据库中获取所有的Topic模型实例，并按照时间升序排列
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
    """添加新主题"""
    # request.method是request对象的一个属性，用于获取 HTTP 请求的方法类型(GET,POST,PUT,DELETE)
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            # new_topic = form.save(commit=False)
            # new_topic.owner = request.user
            new_topic.save()
            # redirect 用于表单提交成功后跳转页面、用户权限验证后跳转到相应页面等场景。
            return redirect('learning_logs:topics')

    # 显示空表单或指出表单数据无效
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

HTML/learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>
    <a href="{% url 'learning_logs:index' %}">学习笔记</a> -
    <a href="{% url 'learning_logs:topics' %}">主题</a>
</p>
{% block content %}
<!-- 内容块留空，等待子模板去填充具体内容 -->
{% endblock content %}
</body>
</html>

HTML/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>
    学习日志可帮助您跟踪您正在学习的任何主题的学习情况。
</p>
{% endblock content %}

HTML/learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
  <p>添加新主题:</p>
  <form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">添加主题</button>
  </form>
{% endblock content %}
</body>
</html>

HTML/learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
  <p>主题: {{ topic.text }}</p>
  <p>条目：</p>
  <ul>
    {% for entry in entries %}
      <li>
        <p>{{ entry.data_added|date:'M d, Y H:i'}}</p>
        <p>{{ entry.text|linebreaks }}</p>
      </li>
    {% empty %}
      <li>没有条目</li>
    {% endfor %}
  </ul>
{% endblock content %}
</body>
</html>

HTML/learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% block content %}
  <p>主题</p>
  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic.text }}</a>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}
</body>
</html>